from orca_engine.archive_validator import (
    ArchiveValidationError,
    OrcaArchiveMetadata,
    validate_orca_tar_xz,
)
from orca_engine.constants import PhysConst
from orca_engine.io import (
    DuplicateSpeciesError,
    discover_orca_files,
    load_directory_parallel,
    parse_path_safe,
)
from orca_engine.models import (
    BDEResult,
    CalcMetadata,
    ConsistencyReport,
    CoordinateUnit,
    EnergyKind,
    JobData,
    MoleculeData,
    OrbitalEnergies,
    Reaction,
    ReactionResult,
    ReactionTerm,
    SpinChannel,
)
from orca_engine.experimental_spectrum import (
    ExperimentalSpectrum,
    ExperimentalSpectrumError,
    build_multi_spectrum_overlay,
    convolute_theoretical_spectrum,
    detect_peaks,
    inspect_experimental_file,
    parse_experimental_excel,
    parse_experimental_multi_series_excel,
    parse_experimental_multi_series_text,
    parse_experimental_text,
)
from orca_engine.nmr import (
    NMR_REFERENCE_CATALOG,
    NMRAtomRecord,
    NMRNucleus,
    NMRPeak,
    NMRReference,
    NMRResult,
    NMRSpectrum,
    OrcaNMRParser,
    build_nmr_spectrum,
    check_reference_compatibility,
    export_nmr_csv,
    export_nmr_json,
)
from orca_engine.parser import OrcaParser
from orca_engine.thermochemistry import ReactionParseError, ThermochemistryEngine

__version__ = "1.0.3"

__all__ = [
    "ArchiveValidationError",
    "BDEResult",
    "CalcMetadata",
    "ConsistencyReport",
    "CoordinateUnit",
    "DuplicateSpeciesError",
    "EnergyKind",
    "ExperimentalSpectrum",
    "ExperimentalSpectrumError",
    "JobData",
    "MoleculeData",
    "NMRAtomRecord",
    "NMRNucleus",
    "NMRPeak",
    "NMRReference",
    "NMRResult",
    "NMRSpectrum",
    "NMR_REFERENCE_CATALOG",
    "OrbitalEnergies",
    "OrcaArchiveMetadata",
    "OrcaArchiveStore",
    "OrcaNMRParser",
    "OrcaParser",
    "PhysConst",
    "Reaction",
    "ReactionParseError",
    "ReactionResult",
    "ReactionTerm",
    "SpinChannel",
    "ThermochemistryEngine",
    "__version__",
    "build_multi_spectrum_overlay",
    "build_nmr_spectrum",
    "check_reference_compatibility",
    "convolute_theoretical_spectrum",
    "detect_peaks",
    "discover_orca_files",
    "export_nmr_csv",
    "export_nmr_json",
    "inspect_experimental_file",
    "load_directory_parallel",
    "parse_experimental_excel",
    "parse_experimental_multi_series_excel",
    "parse_experimental_multi_series_text",
    "parse_experimental_text",
    "parse_path_safe",
    "validate_orca_tar_xz",
]
